import { Resizable } from "@/components/Resizable/Resizable";
import type { Components } from "@/puck/types";

type ResizableProps = Components["Resizable"];

const slotAllow = [
  "Typography",
  "Badge",
  "Button",
  "Image",
  "Checkbox",
  "Card",
  "Accordion",
  "Alert",
  "AlertDialog",
  "AspectRatio",
  "Avatar",
  "Breadcrumb",
  "Calendar",
  "Carousel",
  "Chart",
  "Collapsible",
  "Combobox",
  "Command",
  "ContextMenu",
  "DataTable",
  "DatePicker",
  "Dialog",
  "Drawer",
  "DropdownMenu",
  "Empty",
  "Field",
  "Flex",
  "Grid",
  "HeroCard",
  "HoverCard",
  "Input",
  "InputGroup",
  "Item",
  "Menubar",
  "NavigationMenu",
  "Pagination",
  "Popover",
  "Progress",
  "Resizable",
  "ScrollArea",
  "Section",
  "Select",
  "Sheet",
  "Sidebar",
  "Space",
] as const;

export const resizablePuckConfig = {
  Resizable: {
    label: "Resizable",
    fields: {
      direction: {
        type: "select" as const,
        label: "Direction",
        options: [
          { label: "Horizontal", value: "horizontal" },
          { label: "Vertical", value: "vertical" },
        ],
      },
      autoSaveId: { type: "text", label: "Auto-save ID (persist sizes)" },
      groupDisableCursor: {
        type: "radio" as const,
        label: "Group: disable cursor",
        options: [
          { label: "No", value: false },
          { label: "Yes", value: true },
        ],
      },
      groupDisabled: {
        type: "radio" as const,
        label: "Group: disabled",
        options: [
          { label: "No", value: false },
          { label: "Yes", value: true },
        ],
      },
      groupResizeTargetMinimumSizeCoarse: {
        type: "number" as const,
        label: "Group: resize target min (coarse px)",
        min: 0,
      },
      groupResizeTargetMinimumSizeFine: {
        type: "number" as const,
        label: "Group: resize target min (fine px)",
        min: 0,
      },
      tagName: {
        type: "select" as const,
        label: "Wrapper tag",
        options: [
          { label: "div", value: "div" },
          { label: "section", value: "section" },
        ],
      },
      className: { type: "text", label: "Class name" },
      id: { type: "text", label: "ID" },
      panel1Content: { type: "slot", label: "Panel 1", allow: [...slotAllow] },
      panel1DefaultSize: { type: "number", label: "Panel 1 default size (%)", min: 0, max: 100 },
      panel1MinSize: { type: "number", label: "Panel 1 min size (%)", min: 0, max: 100 },
      panel1MaxSize: { type: "number", label: "Panel 1 max size (%)", min: 0, max: 100 },
      panel1Collapsible: {
        type: "radio" as const,
        label: "Panel 1 collapsible",
        options: [
          { label: "No", value: false },
          { label: "Yes", value: true },
        ],
      },
      panel1CollapsedSize: { type: "number", label: "Panel 1 collapsed size (%)", min: 0, max: 100 },
      panel1Order: { type: "number", label: "Panel 1 order", min: 0 },
      panel1ClassName: { type: "text", label: "Panel 1 class name" },
      panel1Id: { type: "text", label: "Panel 1 ID" },
      panel1Disabled: {
        type: "radio" as const,
        label: "Panel 1 disabled",
        options: [
          { label: "No", value: false },
          { label: "Yes", value: true },
        ],
      },
      panel1GroupResizeBehavior: {
        type: "select" as const,
        label: "Panel 1 resize behavior",
        options: [
          { label: "Preserve relative size", value: "preserve-relative-size" },
          { label: "Preserve pixel size", value: "preserve-pixel-size" },
        ],
      },
      handleWithHandle: {
        type: "radio" as const,
        label: "Handle with grip icon",
        options: [
          { label: "No", value: false },
          { label: "Yes", value: true },
        ],
      },
      handleClassName: { type: "text", label: "Handle class name" },
      handleDisabled: {
        type: "radio" as const,
        label: "Handle disabled",
        options: [
          { label: "No", value: false },
          { label: "Yes", value: true },
        ],
      },
      handleId: { type: "text", label: "Handle ID" },
      panel2Content: { type: "slot", label: "Panel 2", allow: [...slotAllow] },
      panel2DefaultSize: { type: "number", label: "Panel 2 default size (%)", min: 0, max: 100 },
      panel2MinSize: { type: "number", label: "Panel 2 min size (%)", min: 0, max: 100 },
      panel2MaxSize: { type: "number", label: "Panel 2 max size (%)", min: 0, max: 100 },
      panel2Collapsible: {
        type: "radio" as const,
        label: "Panel 2 collapsible",
        options: [
          { label: "No", value: false },
          { label: "Yes", value: true },
        ],
      },
      panel2CollapsedSize: { type: "number", label: "Panel 2 collapsed size (%)", min: 0, max: 100 },
      panel2Order: { type: "number", label: "Panel 2 order", min: 0 },
      panel2ClassName: { type: "text", label: "Panel 2 class name" },
      panel2Id: { type: "text", label: "Panel 2 ID" },
      panel2Disabled: {
        type: "radio" as const,
        label: "Panel 2 disabled",
        options: [
          { label: "No", value: false },
          { label: "Yes", value: true },
        ],
      },
      panel2GroupResizeBehavior: {
        type: "select" as const,
        label: "Panel 2 resize behavior",
        options: [
          { label: "Preserve relative size", value: "preserve-relative-size" },
          { label: "Preserve pixel size", value: "preserve-pixel-size" },
        ],
      },
    },
    defaultProps: {
      direction: "horizontal" as const,
      autoSaveId: "",
      tagName: "div",
      className: "",
      id: "",
      panel1Content: [],
      panel1DefaultSize: 50,
      panel1MinSize: 10,
      panel1MaxSize: 90,
      panel1Collapsible: false,
      panel1CollapsedSize: 0,
      panel1Order: 0,
      panel1ClassName: "",
      panel1Id: "",
      handleWithHandle: false,
      handleClassName: "",
      panel2Content: [],
      panel2DefaultSize: 50,
      panel2MinSize: 10,
      panel2MaxSize: 90,
      panel2Collapsible: false,
      panel2CollapsedSize: 0,
      panel2Order: 1,
      panel2ClassName: "",
      panel2Id: "",
      groupDisableCursor: false,
      groupDisabled: false,
      handleDisabled: false,
      handleId: "",
      panel1Disabled: false,
      panel2Disabled: false,
    } satisfies ResizableProps,
    render: (props: ResizableProps) => <Resizable {...props} />,
  },
};
